name: Publish to gh-pages
on:
  repository_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.13
      uses: actions/setup-python@v1
      with:
        python-version: 3.9.13

 - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    # Build the book
    - name: Build the Static flask app
      run: |
        python freeze.py
    
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build